---
title: "Online Data with R"
output: html_notebook
---

# https://cyberhelp.sesync.org/online-data-with-R-lesson/course/
# Online Data with R
Lesson 6 with Quentin Read

## Lesson Objectives
* Distinguish three ways of acquiring online data
* Break down how web services use HTTP
* Learn R tools for data acquisition

## Specific Achievements
* Programatically acquire data embedded in a web page
* Request data through a REST API
* Use the tidycensus package to acquire data
* Use SQLite for caching

## Why script data acquisition?
* Too time intensive to acquire manually
* Integrate updated or new data
* Reproducibility
* There’s an API between you and the data

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
